# Generated by Django 3.2.12 on 2022-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input1', models.CharField(max_length=122)),
                ('input2', models.CharField(max_length=122)),
                ('input3', models.CharField(max_length=122)),
                ('input4', models.CharField(max_length=122)),
                ('input5', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
